model_name: resnext50_32x4d-unet
encoder: resnext50_32x4d
weights: imagenet
decoder: unet
gdown_id: 15mL8c9OBPk2JIcPb0k6t_NMtH-mKeVWE
weight_size: '122.4 MB'
lr: 8.317637711026709e-05
seed: 42
patience: 5
num_workers: 2
batch_size: 16
image_size: 512
epochs: 31
classes: 2
loss: CE
optimizer: Adam
scheduler: cosine
gpu: False
fast_dev_run: 0
all_data: 1
ds_path: 'data'
selected_folds: 4
bands: ['B02','B03','B04','B08']